# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 10:14
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/images', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0430\u043a\u0446\u0438\u0438')),
                ('tag', models.CharField(choices=[('\u0410\u043a\u0442\u0443\u043b\u044c\u043d\u043e', '\u0410\u043a\u0442\u0443\u043b\u044c\u043d\u043e'), ('\u0413\u043e\u0440\u044f\u0447\u0435\u0435', '\u0413\u043e\u0440\u044f\u0447\u0435\u0435'), ('\u041e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0435', '\u041e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0435')], max_length=255, verbose_name='\u0422\u044d\u0433')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442 \u0430\u043a\u0446\u0438\u0438')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0430\u043a\u0446\u0438\u044e',
                'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b \u0430\u043a\u0438\u0439',
            },
        ),
    ]
