# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='phone_number',
            field=models.CharField(default='0700607628', max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
            preserve_default=False,
        ),
    ]
