# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-05 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-timestamp'], 'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c', 'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439'},
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Tag', verbose_name='Tags'),
        ),
    ]
