# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0412\u0438\u0434\u0435\u043e \u0441\u0441\u044b\u043b\u043a\u0430 \u0441 YouTube'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
    ]
