# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180207_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_img',
            field=models.CharField(default=1, editable=False, max_length=1000, verbose_name='thumbnail'),
            preserve_default=False,
        ),
    ]
