# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_video_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('actual', '\u0410\u043a\u0442\u0443\u043b\u044c\u043d\u043e'), ('hot', '\u0413\u043e\u0440\u044f\u0447\u0435\u0435'), ('notify', '\u041e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0435')], default=1, max_length=255, verbose_name='\u0422\u044d\u0433'),
            preserve_default=False,
        ),
    ]
