# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_share_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('\u0410\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u043e', '\u0410\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u043e'), ('\u0413\u043e\u0440\u044f\u0447\u0435\u0435', '\u0413\u043e\u0440\u044f\u0447\u0435\u0435'), ('\u041e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0435', '\u041e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0435')], max_length=255, verbose_name='\u0422\u044d\u0433'),
        ),
    ]
