# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180312_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Tag', verbose_name='\u0422\u0438\u043f \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
    ]
