# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0002_auto_20180215_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
    ]
