# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0004_auto_20180217_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='like_counts',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043b\u0430\u0439\u043a\u043e\u0439'),
        ),
    ]
