# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcourt',
            options={'verbose_name': '\u043e\u0431\u044a\u0435\u043a\u0442', 'verbose_name_plural': '\u0424\u0443\u0434\u043a\u043e\u0440\u0442'},
        ),
    ]
