# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutasiamall_advertiser_lessee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser',
            options={'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442', 'verbose_name_plural': '\u0420\u0435\u043a\u043b\u0430\u043c\u043e\u0434\u0430\u0442\u0435\u043b\u044f\u043c'},
        ),
        migrations.AlterModelOptions(
            name='lessee',
            options={'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442', 'verbose_name_plural': '\u0410\u0440\u0435\u043d\u0434\u0430\u0442\u043e\u0440\u0430\u043c'},
        ),
        migrations.AddField(
            model_name='advertiser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertiser',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430 \u21161'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430 \u21162'),
        ),
        migrations.AddField(
            model_name='lessee',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessee',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430 \u21161'),
        ),
        migrations.AddField(
            model_name='lessee',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430 \u21162'),
        ),
    ]
