# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advertiser_commercial_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='\u0424\u0418\u041e')),
                ('phone', models.CharField(max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('square', models.CharField(max_length=255, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('type_of_product', models.CharField(max_length=255, verbose_name='\u0422\u0438\u043f \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('brand', models.CharField(max_length=255, verbose_name='\u0411\u0440\u0435\u043d\u0434')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u044f\u0432\u043a\u0443',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0430\u0440\u0435\u043d\u0434\u0443',
            },
        ),
    ]
