# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180215_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceid',
            name='fcm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token', to='fcm_django.FCMDevice', verbose_name='FCM Device'),
        ),
    ]
