# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180215_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceid',
            name='fcm',
        ),
        migrations.DeleteModel(
            name='DeviceId',
        ),
    ]
