# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-12 12:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180312_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='text_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='lessee',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='lessee',
            name='text_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='lessee',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='lessee',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='lessee',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='lessee',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
