# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='service_for',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='shop_category', to='shops.Category', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
