# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20180207_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/shops', verbose_name='Logotype'),
        ),
    ]
