# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shoplike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoplike',
            options={'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442', 'verbose_name_plural': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432'},
        ),
        migrations.AddField(
            model_name='shop',
            name='like_counts',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043b\u0430\u0439\u043a\u043e\u0439'),
        ),
    ]
